### ISSUE TITLE
Exception thrown when running screenshots while emulator is already running

### ISSUE THREAD

**Issue by tomwassing** [mmcc007/screenshots#102]
I am getting an exception every time the emulator is already running. I also notice that it tries to write the screenshots to `nullScreenshots`. Apart from these issue a great tool! Thank you very much.

```
Starting flutter daemon...
Clearing images in android/fastlane/metadata/android/en-US/images/nullScreenshots for 'Nexus 6'...
Clearing images in android/fastlane/metadata/android/nl-NL/images/nullScreenshots for 'Nexus 6'...
Unhandled exception:
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("name")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _findDevice.<anonymous closure> (package:screenshots/src/run.dart:386:60)
#2      _ListBase&Object&ListMixin.firstWhere (dart:collection/list.dart:137:15)
#3      _findDevice (package:screenshots/src/run.dart:374:26)
#4      runTestsOnAll (package:screenshots/src/run.dart:135:20)
<asynchronous suspension>
#5      run (package:screenshots/src/run.dart:64:9)
<asynchronous suspension>
#6      main (file:///Users/tom/.pub-cache/hosted/pub.dartlang.org/screenshots-1.3.0/bin/main.dart:85:9)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**emulator -list-avds**
```
Nexus
Nexus_6_API_28
Pixel_2_API_28
```

**adb devices**
```
List of devices attached
adb server version (41) doesn't match this client (40); killing...
* daemon started successfully
emulator-5554	device
```

**screenshots.yaml**
```
# A list of screen capture tests
# Note: flutter driver expects a pair of files eg, main1.dart and main1_test.dart
tests:
  - test_driver/screenshots.dart

# Interim location of screenshots from tests
staging: /tmp/screenshots

# A list of locales supported by the app
locales:
  - en-US
  - nl-NL

# A map of devices to emulate
devices:
#  ios:
#    iPhone XS Max:
#      frame: false
#    iPad Pro (12.9-inch) (3rd generation):
#      orientation: LandscapeRight
  android:
    Nexus 6:
      frame: false

# Frame screenshots
frame: true
```

**flutter doctor -v**
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-NL)
    • Flutter version 1.7.8+hotfix.4 at /Users/tom/dev/flutter
    • Framework revision 20e59316b8 (5 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tom/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/tom/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by ened** [comment]
This also seems to happen when no devices are connected at all. (trying to take iOS screenshots).

**Comment by mmcc007** [comment]
Wasn't able to reproduce the exception using the currently release screenshots (v1.3.0) with your screenshots.yaml on my setup. Are you on the same version of screenshots?

Try running it using the current master version:
```
pub global activate --source git https://github.com/mmcc007/screenshots.git
```

The null in the fastlane path happens on android devices when you select a device that has no supported screen and framing is disabled on that device. 

Looks like will have to add a required parameter to the device config in sylph.yaml to provide the device type (phone/sevenInch/tenInch) or default to 'phone' and provide a warning with hint to provide the device type to the device config. (Finding the device type would require the user to do some googling of the particular device).

As a further enhancement, can add some device types to screens.yaml, as they are identified, to avoid having to add the parameter to the device (for those identified devices).

**Comment by mmcc007** [comment]
Added an enhancement to set the fastlane dir using a default.
Also added entries in screens.yaml for identified devices.

You can try it out with:
```
git clone https://github.com/mmcc007/sylph.git
git checkout #102_fastlane_path
pub global activate --source path .
```
