### ISSUE TITLE
Screenshots moved to invalid directory and ends with exception

### ISSUE THREAD

**Issue by tomwassing** [mmcc007/screenshots#103]
The tool uses the directory `nullScreenshots` to save the screenshots. This happens when the tool launches and clears the directory and when it moves the files.

**Log**
```
Starting flutter daemon...
Clearing images in android/fastlane/metadata/android/en-US/images/nullScreenshots for 'Nexus 6'...
Clearing images in android/fastlane/metadata/android/nl-NL/images/nullScreenshots for 'Nexus 6'...
Starting Nexus 6...
'Nexus 6' locale: en-US, test locale: en-US
Running test_driver/screenshots.dart on 'Nexus 6' in locale en-US...
Starting application: test_driver/screenshots.dart
Initializing gradle...                                              0.8s
Resolving dependencies...                                           3.2s
Installing build/app/outputs/apk/app.apk...                         3.0s
Running Gradle task 'assembleDebug'...                              5.8s
Built build/app/outputs/apk/debug/app-debug.apk.
I/flutter (13493): Observatory listening on http://127.0.0.1:35177/2f9DxDMDQ0U=/
00:00 +0: screenshots (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:51951/2f9DxDMDQ0U=/
[trace] FlutterDriver: Isolate found with number: 996956704
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
I/flutter (13493): _onCreate 2
I/flutter (13493): creating v1
I/flutter (13493): migrate1To2
I/flutter (13493): crateVersion2
[warning] FlutterDriver: request_data message is taking a long time to complete...
00:20 +0: screenshots Trips overview
Screenshot trips-overview created
00:37 +1: screenshots Reports overview
Screenshot reports-overview created
00:41 +2: screenshots Report screen
Screenshot report created
00:45 +3: screenshots (tearDownAll)
00:45 +3: All tests passed!
Stopping application instance.
Warning: 'Nexus 6' images will not be processed
Moving screenshots to android/fastlane/metadata/android/en-US/images/nullScreenshots
adb server version (41) doesn't match this client (40); killing...
ADB server didn't ACK
Full server startup log: /var/folders/2c/c78qnt9s173_pflmcmbplx780000gn/T//adb.501.log
Server had pid: 15270
--- adb starting (pid 15270) ---
adb I 08-20 22:13:37 15270 88830 main.cpp:56] Android Debug Bridge version 1.0.40
adb I 08-20 22:13:37 15270 88830 main.cpp:56] Version 4986621
adb I 08-20 22:13:37 15270 88830 main.cpp:56] Installed as /usr/local/bin/adb
adb I 08-20 22:13:37 15270 88830 main.cpp:56] 
adb E 08-20 22:13:37 15270 88833 usb_osx.cpp:159] Unable to create an interface plug-in (e00002be)
adb I 08-20 22:13:37 15270 88830 auth.cpp:421] adb_auth_init...
adb I 08-20 22:13:37 15270 88830 auth.cpp:174] read_key_file '/Users/tom/.android/adbkey'...
adb I 08-20 22:13:37 15270 88837 transport.cpp:281] emulator-5554: read thread spawning
adb I 08-20 22:13:37 15270 88838 transport.cpp:294] emulator-5554: write thread spawning
adb I 08-20 22:13:37 15270 88830 adb.cpp:141] emulator-5554: already offline
adb E 08-20 22:13:38 15270 88833 usb_osx.cpp:159] Unable to create an interface plug-in (e00002be)
adb server killed by remote request
adb I 08-20 22:13:38 15270 88830 transport.cpp:337] BlockingConnectionAdapter(emulator-5554): stopping
adb I 08-20 22:13:38 15270 88837 transport.cpp:285] emulator-5554: read failed: Bad file descriptor
adb I 08-20 22:13:38 15270 88830 transport.cpp:355] BlockingConnectionAdapter(emulator-5554): stopped

* failed to start daemon
error: cannot connect to daemon
Unhandled exception:
command failed: exitcode=1, cmd='adb -s emulator-5554 shell getprop persist.sys.locale', workingDir=., silent=true
#0      cmd (package:screenshots/src/run.dart:535:5)
#1      getAndroidDeviceLocale (package:screenshots/src/utils.dart:173:19)
#2      setEmulatorLocale (package:screenshots/src/run.dart:418:24)
<asynchronous suspension>
#3      runTestsOnAll (package:screenshots/src/run.dart:219:17)
<asynchronous suspension>
#4      run (package:screenshots/src/run.dart:64:9)
<asynchronous suspension>
#5      main (file:///Users/tom/.pub-cache/hosted/pub.dartlang.org/screenshots-1.3.0/bin/main.dart:85:9)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**screenshots.yaml**
```
# A list of screen capture tests
# Note: flutter driver expects a pair of files eg, main1.dart and main1_test.dart
tests:
  - test_driver/screenshots.dart

# Interim location of screenshots from tests
staging: /tmp/screenshots

# A list of locales supported by the app
locales:
  - en-US
  - nl-NL

# A map of devices to emulate
devices:
#  ios:
#    iPhone XS Max:
#      frame: false
#    iPad Pro (12.9-inch) (3rd generation):
#      orientation: LandscapeRight
  android:
    Nexus 6:
      frame: false

# Frame screenshots
frame: true
```

**flutter doctor -v**
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-NL)
    • Flutter version 1.7.8+hotfix.4 at /Users/tom/dev/flutter
    • Framework revision 20e59316b8 (5 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tom/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/tom/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by mmcc007** [comment]
Other then the null issue which is being addressed in #102, it looks like there may be a setup issue related to adb on your machine. 

Try:
```
adb -s emulator-5554 shell getprop persist.sys.locale
```
from command line.
