### ISSUE TITLE
ios + travis :: exception starting driver test

### ISSUE THREAD

**Issue by zanuka** [mmcc007/screenshots#11]
I've got the ios screenshot job to start in travis, however it's throwing an exception when trying to start my driver test `test_driver/smoke.dart`

`Application failed to start. Will not run test. Quitting.`

```
Upgrading project.pbxproj of Runner.app' to include the 'flutter_assets' directory
Running pod install...                                           2.8s
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Finding Podfile changes
      - Crashlytics
      - Fabric
      - Flutter
      - background_fetch
      - connectivity
      - device_info
      - flutter_background_geolocation
      - flutter_crashlytics
      - flutter_local_notifications
      - geocoder
      - local_auth
      - package_info
      - path_provider
      - shared_preferences
      - sqflite
      - url_launcher
    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `background_fetch` from `.symlinks/plugins/background_fetch/ios`
    -> Fetching podspec for `connectivity` from `.symlinks/plugins/connectivity/ios`
    -> Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
    -> Fetching podspec for `flutter_background_geolocation` from `.symlinks/plugins/flutter_background_geolocation/ios`
    -> Fetching podspec for `flutter_crashlytics` from `.symlinks/plugins/flutter_crashlytics/ios`
    -> Fetching podspec for `flutter_local_notifications` from `.symlinks/plugins/flutter_local_notifications/ios`
    -> Fetching podspec for `geocoder` from `.symlinks/plugins/geocoder/ios`
    -> Fetching podspec for `local_auth` from `.symlinks/plugins/local_auth/ios`
    -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "Crashlytics":
      In snapshot (Podfile.lock):
        Crashlytics (= 3.12.0)
      In Podfile:
        flutter_crashlytics (from `.symlinks/plugins/flutter_crashlytics/ios`) was resolved to 0.0.1, which depends on
          Crashlytics
    It seems like you've changed the constraints of dependency `Crashlytics` inside your development pod `flutter_crashlytics`.
    You should run `pod update Crashlytics` to apply changes you've made.
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:308:in `tap'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:182:in `resolve'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/molinillo-0.6.5/lib/molinillo/resolver.rb:43:in `resolve'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:123:in `resolve'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:781:in `block in resolve_dependencies'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:779:in `resolve_dependencies'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:88:in `analyze'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /Users/travis/.rvm/gems/ruby-2.4.3/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /Users/travis/.rvm/gems/ruby-2.4.3/bin/pod:23:in `load'
    /Users/travis/.rvm/gems/ruby-2.4.3/bin/pod:23:in `<main>'
    /Users/travis/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `eval'
    /Users/travis/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `<main>'
Error running pod install
Application failed to start. Will not run test. Quitting.
Unhandled exception:
command failed: cmd='flutter drive test_driver/smoke.dart'
#0      streamCmd (package:screenshots/utils.dart:63:7)
<asynchronous suspension>
#1      screenshots (package:screenshots/screenshots.dart:100:9)
<asynchronous suspension>
#2      run (package:screenshots/screenshots.dart:70:17)
<asynchronous suspension>
#3      main (file:///Users/travis/.pub-cache/hosted/pub.dartlang.org/screenshots-0.1.4/bin/main.dart:63:9)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
The command "screenshots" exited with 255.
```

the `- tar cvzf ` and `zip -r` jobs proceed with 0 exit codes although there aren't any images stored to archive

**Comment by mmcc007** [comment]
This is unlikely to be a Screenshots issue. 

But it could be a versioning issue with how your build is set-up in Travis. You can try changing the version of XCode, cocoapods, etc... 

For example, you can change the version of XCode using:
```
osx_image: xcode10.1
```
(the default is 9.4)

**Comment by zanuka** [comment]
yeah this can just be closed out for now, is likely un-related
