### ISSUE TITLE
update intl dependency to 0.16.0

### ISSUE THREAD

**Issue by joeblew99** [mmcc007/screenshots#132]
i had to pump it to 16 to make it happy. Can confirm everything works well then.
I am on flutter master. 

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0

**Comment by mmcc007** [comment]
Thanks for the heads-up
Intl dependency has been updated to `  intl: ">=0.15.0 <1.0.0"` (#125) and is in the current release (v2.0.2+1). Should work for foreseeable future on stable channel (which is what screenshots supports). I expect this should also work on master channel. 

Are you running on v2.0.2+1?

**Comment by joeblew99** [comment]
yes version: 2.0.2+1
I am on MASTER channel.

I just did an uninstall and install. It runs fine now.
All good. closing :)

**Comment by mmcc007** [comment]
Thnks for the feedback

**Comment by joeblew99** [comment]
Spoke too soon

````
x-MacBook-Pro:screenshots apple$ pub global activate screenshots
Resolving dependencies... (4.7s)
+ archive 2.0.10
+ args 1.5.2
+ charcode 1.1.2
+ collection 1.14.12
+ convert 2.1.1
+ crypto 2.1.3
+ file 5.0.10
+ intl 0.16.0
+ meta 1.1.7
+ path 1.6.4
+ platform 2.2.1
+ process 3.0.12
+ resource 2.1.6
+ screenshots 2.0.2+1
+ source_span 1.5.5
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ tool_base 1.9.5+1
+ tool_mobile 1.9.5+1
+ typed_data 1.1.6
+ yaml 2.1.16
Precompiling executables... (6.8s)
Precompiled screenshots:main.
Installed executable screenshots.
Activated screenshots 2.0.2+1.

cd /Users/apple/workspace/go/src/github.com/mmcc007/screenshots/example/ && screenshots
Starting flutter daemon...                                          1.5s
Clearing images in ios/fastlane/screenshots/en-US for 'iPad Pro (12.9-inch) (2nd generation)'...
Clearing images in ios/fastlane/screenshots/fr-CA for 'iPad Pro (12.9-inch) (2nd generation)'...
Starting iPad Pro (12.9-inch) (2nd generation)...
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
Unable to boot device in current state: Booted


Unhandled exception:
command failed: exitcode=164, cmd='xcrun simctl boot 415D67D6-4BF2-4323-BB87-44787F8A4865', workingDir=.
#0      cmd (package:screenshots/src/utils.dart:360:5)
#1      startSimulator (package:screenshots/src/run.dart:408:3)
<asynchronous suspension>
#2      runTestsOnAll (package:screenshots/src/run.dart:225:17)
<asynchronous suspension>
#3      runScreenshots (package:screenshots/src/run.dart:109:9)
<asynchronous suspension>
#4      screenshots.<anonymous closure> (package:screenshots/src/run.dart:45:14)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:153:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:tool_base/src/base/context.dart:152:18)
<asynchronous suspension>
#11     runInContext (package:screenshots/src/context_runner.dart:16:24)
<asynchronous suspension>
#12     screenshots (package:screenshots/src/run.dart:44:12)
<asynchronous suspension>
#13     main (file:///Users/apple/.pub-cache/hosted/pub.dartlang.org/screenshots-2.0.2+1/bin/main.dart:102:25)
<asynchronous suspension>
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
make: *** [flu-screenshot-run] Error 255
````
