### ISSUE TITLE
Not able to take screenshots after first driver use

### ISSUE THREAD

**Issue by troovers** [mmcc007/screenshots#139]
My tests are only capable of creating one screenshot, and that is before the use of the driver to execute test logic. In this case, the first screenshot ("screenshot0") is being created, but when trying to create the second one, "screenshot1", the process crashes. Executing the test logic inside `await driver.runUnsynchronized()` is necessary, because of a "bug" with `flutter_driver`.

```
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';
import 'package:screenshots/screenshots.dart';

void main() {
  group('ClubApp', () {
    final config = Config();

    FlutterDriver driver;

    // Connect to the Flutter driver before running any tests.
    setUpAll(() async {
      driver = await FlutterDriver.connect();
    });

    // Close the connection to the driver after the tests have completed.
    tearDownAll(() async {
      if (driver != null) {
        driver.close();
      }
    });

    test('Starts at onboarding', () async {
      await screenshot(driver, config, 'screenshot0');

      await driver.runUnsynchronized(() async {
        await driver.tap(find.byValueKey('onboarding_start_button'));
      });

      expect(true, true);
    });

    test('Navigation to login screen', () async {
      await driver.runUnsynchronized(() async {
        await driver.waitFor(find.byValueKey('login_email_field'));
      });

      await screenshot(driver, config, 'screenshot1');

      await driver.runUnsynchronized(() async {
        await driver.tap(find.byValueKey('login_submit_button'));
      });

      expect(true, true);
    });
  });
}
```

**Logs**

```Using device iPhone Xʀ.
Starting application: test_driver/main.dart
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                          10,9s
 └─Compiling, linking and signing...                         7,9s
Xcode build done.                                           25,0s
	path: satisfied (Path is satisfied), interface: en0
[Crashlytics] Version 3.14.0 (144)
flutter: Observatory listening on http://127.0.0.1:60874/76Kkt99gAQg=/
	path: satisfied (Path is satisfied), interface: en0
[Fabric] [Fabric +with] called multiple times. Only the first call is honored, please pass all kits you wish to
initialize
	path: satisfied (Path is satisfied), interface: en0
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
	[C3.1 2F570707-E53D-482A-A679-DC187D9465F1 192.168.86.250:60877<->172.217.168.202:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.596s, DNS @0.003s took 0.018s, TCP @0.022s took 0.017s, TLS took 0.526s
	bytes in/out: 5207/1297, packets in/out: 8/10, rtt: 0.014s, retransmitted packets: 0, out-of-order packets: 0
	[C1.1 2435227D-3B23-4510-8075-CA270E940BCA 192.168.86.250:60875<->107.20.142.207:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.777s, DNS @0.003s took 0.096s, TCP @0.139s took 0.124s, TLS took 0.338s
	bytes in/out: 7204/1595, packets in/out: 7/3, rtt: 0.120s, retransmitted packets: 0, out-of-order packets: 0
00:00 +0: ClubApp (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:60874/76Kkt99gAQg=/
[trace] FlutterDriver: Isolate found with number: 3731913691742979
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
flutter:
\^[[38;5;12m┌─────────────────────────────────────────────────────────────────────────────────────────────────────────
──────────────<…>
flutter: \^[[38;5;12m│ #0   new LoggerService._initiate
(package:clubapp/src/resources/services/logger_service.dart:10:1<…>
flutter: \^[[38;5;12m│ #1   LoggerService._instance (package:clubapp/src/resources/services/logger_service.dart:4:5<…>
flutter:
\^[[38;5;12m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;12m│ 💡 LoggerService initiated<…>
flutter:
\^[[38;5;12m└─────────────────────────────────────────────────────────────────────────────────────────────────────────
──────────────<…>
flutter:
\^[[38;5;12m┌─────────────────────────────────────────────────────────────────────────────────────────────────────────
──────────────<…>
flutter: \^[[38;5;12m│ #0   LoggerService.info (package:clubapp/src/resources/services/logger_service.dart:14:1<…>
flutter: \^[[38;5;12m│ #1   new NotificationManager._initiate
(package:clubapp/src/resources/managers/notification_manager.dart:14:1<…>
flutter:
\^[[38;5;12m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;12m│ 💡 Initiating NotificationManager()<…>
flutter:
\^[[38;5;12m└─────────────────────────────────────────────────────────────────────────────────────────────────────────
──────────────<…>
flutter: Started app with environment: AppEnvironment.staging
[info ] FlutterDriver: Connected to Flutter application.
00:01 +0: ClubApp Starts at onboarding
flutter: Sending request: GET, /customers/themes, content: null
flutter:
\^[[38;5;12m┌─────────────────────────────────────────────────────────────────────────────────────────────────────────
──────────────<…>
flutter: \^[[38;5;12m│ #0   LoggerService.info (package:clubapp/src/resources/services/logger_service.dart:14:1<…>
flutter: \^[[38;5;12m│ #1   AuthManager.registerDevice
(package:clubapp/src/resources/managers/auth_manager.dart:131:1<…>
flutter:
\^[[38;5;12m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;12m│ 💡 Not registering device, no Firebase Cloud Messaging token present<…>
flutter:
\^[[38;5;12m└─────────────────────────────────────────────────────────────────────────────────────────────────────────
──────────────<…>
flutter:
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
──
flutter: │ #0   LoggerService.debug (package:clubapp/src/resources/services/logger_service.dart:18:13)
flutter: │ #1   new ApiProvider._initiate.() (package:clubapp/src/resources/api/api_prodiver.dart:98:18)
flutter:
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
┄┄
flutter: │ 🐛 Received response: {data: {default: {primary: 5e72e4, primary_dark: 4b5bb6, primary_light: 7e8ee9,
bright_primary_contrast: true, text: 222222}, ttvsmash: {primary: 009A00, primary_dark: 1aa51a, primary_light: 008b00,
bright_primary_contrast: true, text: 222222}}}
flutter:
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
──
	[C6.1 0AF19692-F3DE-417A-BDB9-7374FE0B116B 192.168.86.250:60892<->172.217.168.206:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.155s, DNS @0.001s took 0.003s, TCP @0.006s took 0.017s, TLS took 0.078s
	bytes in/out: 4483/1017, packets in/out: 8/9, rtt: 0.017s, retransmitted packets: 0, out-of-order packets: 0
	[C7.1 F93C7275-4752-4857-BF95-0F1AC99674DE 192.168.86.250:60893<->172.217.168.206:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.121s, DNS @0.000s took 0.004s, TCP @0.005s took 0.016s, TLS took 0.074s
	bytes in/out: 4184/1531, packets in/out: 8/11, rtt: 0.015s, retransmitted packets: 0, out-of-order packets: 0
00:31 +0 -1: ClubApp Starts at onboarding [E]
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.
  package:test_api/src/backend/invoker.dart 332:28              Invoker._handleError.<fn>
  dart:async/zone.dart 1120:38                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  package:test_api/src/backend/invoker.dart 330:10              Invoker._handleError
  package:test_api/src/backend/invoker.dart 283:9               Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  package:test_api/src/backend/invoker.dart 281:38              Invoker.heartbeat.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 947:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 21:15                       Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 382:19                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 416:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 172:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 946:22                                   _CustomZone.bindCallback
  dart:async/zone.dart 1191:21                                  _rootCreateTimer
  dart:async/zone.dart 1088:19                                  _CustomZone.createTimer
  package:test_api/src/backend/invoker.dart 280:34              Invoker.heartbeat
  package:test_api/src/backend/invoker.dart 243:5               Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 166:33             Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 1516:10                                  _runZoned
  dart:async/zone.dart 1463:12                                  runZoned
  package:test_api/src/backend/declarer.dart 165:13             Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                   new Timer
  dart:async/timer.dart 87:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 399:21              Invoker._onRun.<fn>.<fn>.<fn>

[warning] FlutterDriver: waitUntilNoTransientCallbacks message is taking a long time to complete...
00:31 +0 -1: ClubApp Navigation to login screen
00:31 +0 -1: ClubApp Starts at onboarding [E]
  DriverError: Error in Flutter application: Timeout while executing waitUntilNoTransientCallbacks: TimeoutException after 0:00:30.000000: Future not completed
  #0      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:198:31)
  <asynchronous suspension>
  #1      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:512:32)
  <asynchronous suspension>
  #2      _runExtension (dart:developer-patch/developer.dart:84:23)

  Original error: null
  Original stack trace:
  null

  package:flutter_driver/src/driver/driver.dart 455:7  FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1062:19                         _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 80:23              _asyncErrorWrapperHelper
  package:test_api/src/backend/invoker.dart            Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1124:13                         _rootRun
  dart:async/zone.dart 1021:19                         _CustomZone.run
  dart:async/zone.dart 1516:10                         _runZoned
  dart:async/zone.dart 1463:12                         runZoned
  package:test_api/src/backend/invoker.dart 247:5      Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 166:33    Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1124:13                         _rootRun
  dart:async/zone.dart 1021:19                         _CustomZone.run
  dart:async/zone.dart 1516:10                         _runZoned
  dart:async/zone.dart 1463:12                         runZoned
  package:test_api/src/backend/declarer.dart 165:13    Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                         _CustomZone.registerCallback
  dart:async/zone.dart 962:22                          _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                          new Timer
  dart:async/timer.dart 87:9                           Timer.run
  dart:async/future.dart 174:11                        new Future
  package:test_api/src/backend/invoker.dart 399:21     Invoker._onRun.<fn>.<fn>.<fn>

[warning] FlutterDriver: waitFor message is taking a long time to complete...
01:01 +0 -2: ClubApp Navigation to login screen [E]
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.
  package:test_api/src/backend/invoker.dart 332:28              Invoker._handleError.<fn>
  dart:async/zone.dart 1120:38                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  package:test_api/src/backend/invoker.dart 330:10              Invoker._handleError
  package:test_api/src/backend/invoker.dart 283:9               Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  package:test_api/src/backend/invoker.dart 281:38              Invoker.heartbeat.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 947:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 21:15                       Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 382:19                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 416:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 172:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 946:22                                   _CustomZone.bindCallback
  dart:async/zone.dart 1191:21                                  _rootCreateTimer
  dart:async/zone.dart 1088:19                                  _CustomZone.createTimer
  package:test_api/src/backend/invoker.dart 280:34              Invoker.heartbeat
  package:test_api/src/backend/invoker.dart 243:5               Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 166:33             Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 1516:10                                  _runZoned
  dart:async/zone.dart 1463:12                                  runZoned
  package:test_api/src/backend/declarer.dart 165:13             Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                   new Timer
  dart:async/timer.dart 87:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 399:21              Invoker._onRun.<fn>.<fn>.<fn>

01:01 +0 -2: ClubApp Navigation to calendar screen
01:01 +1 -2: ClubApp (tearDownAll)
01:01 +1 -2: ClubApp Navigation to login screen [E]
  Bad state: The client is closed.
  package:json_rpc_2/src/client.dart 139:19                     Client._send
  package:json_rpc_2/src/client.dart 107:5                      Client.sendRequest
  package:json_rpc_2/src/peer.dart 79:15                        Peer.sendRequest
  package:vm_service_client/src/scope.dart 64:23                Scope.sendRequestRaw
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1062:19                                  _CustomZone.registerBinaryCallback
  dart:async/future_impl.dart 802:10                            _registerErrorHandler
  dart:async/future_impl.dart 278:19                            Future.then
  dart:async/future_impl.dart 773:10                            Future.timeout
  package:flutter_driver/src/driver/driver.dart 105:18          _warnIfSlow
  package:flutter_driver/src/driver/driver.dart 441:24          FlutterDriver._sendCommand
  dart:async-patch/async_patch.dart 43:6                        _AsyncAwaitCompleter.start
  package:flutter_driver/src/driver/driver.dart 432:44          FlutterDriver._sendCommand
  package:flutter_driver/src/driver/driver.dart 1023:13         FlutterDriver.runUnsynchronized
  dart:async-patch/async_patch.dart 78:45                       _asyncErrorWrapperHelper.<fn>
  package:stack_trace/src/stack_zone_specification.dart 141:26  StackZoneSpecification._registerBinaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 141:14  StackZoneSpecification._registerBinaryCallback.<fn>
  dart:async/zone.dart 1144:38                                  _rootRunBinary
  dart:async/zone.dart 1037:19                                  _CustomZone.runBinary
  dart:async/future_impl.dart 151:20                            _FutureListener.handleError
  dart:async/future_impl.dart 690:47                            Future._propagateToListeners.handleError
  dart:async/future_impl.dart 711:24                            Future._propagateToListeners
  dart:async/future_impl.dart 530:5                             Future._completeError
  dart:async-patch/async_patch.dart 36:15                       _AsyncAwaitCompleter.completeError
  test_driver/main_test.dart                                    main.<fn>.<fn>.<fn>
  dart:async-patch/async_patch.dart 78:45                       _asyncErrorWrapperHelper.<fn>
  package:stack_trace/src/stack_zone_specification.dart 141:26  StackZoneSpecification._registerBinaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 141:14  StackZoneSpecification._registerBinaryCallback.<fn>
  dart:async/zone.dart 1144:38                                  _rootRunBinary
  dart:async/zone.dart 1037:19                                  _CustomZone.runBinary
  dart:async/future_impl.dart 151:20                            _FutureListener.handleError
  dart:async/future_impl.dart 690:47                            Future._propagateToListeners.handleError
  dart:async/future_impl.dart 711:24                            Future._propagateToListeners
  dart:async/future_impl.dart 530:5                             Future._completeError
  dart:async-patch/async_patch.dart 36:15                       _AsyncAwaitCompleter.completeError
  package:flutter_driver/src/driver/driver.dart                 FlutterDriver.waitFor
  dart:async-patch/async_patch.dart 78:45                       _asyncErrorWrapperHelper.<fn>
  package:stack_trace/src/stack_zone_specification.dart 141:26  StackZoneSpecification._registerBinaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 141:14  StackZoneSpecification._registerBinaryCallback.<fn>
  dart:async/zone.dart 1144:38                                  _rootRunBinary
  dart:async/zone.dart 1037:19                                  _CustomZone.runBinary
  dart:async/future_impl.dart 151:20                            _FutureListener.handleError
  dart:async/future_impl.dart 690:47                            Future._propagateToListeners.handleError
  dart:async/future_impl.dart 711:24                            Future._propagateToListeners
  dart:async/future_impl.dart 530:5                             Future._completeError
  dart:async-patch/async_patch.dart 36:15                       _AsyncAwaitCompleter.completeError
  package:flutter_driver/src/driver/driver.dart                 FlutterDriver._sendCommand
  dart:async-patch/async_patch.dart 78:45                       _asyncErrorWrapperHelper.<fn>
  package:stack_trace/src/stack_zone_specification.dart 141:26  StackZoneSpecification._registerBinaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 141:14  StackZoneSpecification._registerBinaryCallback.<fn>
  dart:async/zone.dart 1144:38                                  _rootRunBinary
  dart:async/zone.dart 1037:19                                  _CustomZone.runBinary
  dart:async/future_impl.dart 151:20                            _FutureListener.handleError
  dart:async/future_impl.dart 690:47                            Future._propagateToListeners.handleError
  dart:async/future_impl.dart 711:24                            Future._propagateToListeners
  dart:async/future_impl.dart 530:5                             Future._completeError
  dart:async-patch/async_patch.dart 36:15                       _AsyncAwaitCompleter.completeError
  package:vm_service_client/src/scope.dart                      Scope.sendRequestRaw
  dart:async-patch/async_patch.dart 78:45                       _asyncErrorWrapperHelper.<fn>
  package:stack_trace/src/stack_zone_specification.dart 141:26  StackZoneSpecification._registerBinaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 141:14  StackZoneSpecification._registerBinaryCallback.<fn>
  dart:async/zone.dart 1144:38                                  _rootRunBinary
  dart:async/zone.dart 1037:19                                  _CustomZone.runBinary
  dart:async/future_impl.dart 151:20                            _FutureListener.handleError
  dart:async/future_impl.dart 690:47                            Future._propagateToListeners.handleError
  dart:async/future_impl.dart 711:24                            Future._propagateToListeners
  dart:async/future_impl.dart 530:5                             Future._completeError
  dart:async/future_impl.dart 55:12                             _SyncCompleter._completeError
  dart:async/future_impl.dart 27:5                              _Completer.completeError
  package:json_rpc_2/src/client.dart 67:27                      new Client.withoutJson.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1120:38                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/future_impl.dart 161:18                            _FutureListener.handleWhenComplete
  dart:async/future_impl.dart 648:39                            Future._propagateToListeners.handleWhenCompleteCallback
  dart:async/future_impl.dart 704:37                            Future._propagateToListeners
  dart:async/future_impl.dart 605:9                             Future._propagateToListeners
  dart:async/future_impl.dart 522:5                             Future._completeWithValue
  dart:async/future_impl.dart 552:7                             Future._asyncComplete.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 923:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 963:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                      _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                       _startMicrotaskLoop
  dart:isolate-patch/timer_impl.dart 391:30                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 416:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 172:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1062:19                                  _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 80:23                       _asyncErrorWrapperHelper
  package:flutter_driver/src/driver/driver.dart                 FlutterDriver.runUnsynchronized
  test_driver/main_test.dart 35:20                              main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 71:23                       _asyncThenWrapperHelper
  package:test_api/src/backend/declarer.dart                    Declarer.test.<fn>.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 250:15              Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                   new Timer
  dart:async/timer.dart 87:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 399:21              Invoker._onRun.<fn>.<fn>.<fn>

  DriverError: Failed to fulfill SetFrameSync due to remote error
  Original error: Bad state: The client is closed.
  Original stack trace:
  #0      Client._send (package:json_rpc_2/src/client.dart:139:19)
  #1      Client.sendRequest (package:json_rpc_2/src/client.dart:107:5)
  #2      Peer.sendRequest (package:json_rpc_2/src/peer.dart:79:15)
  #3      Scope.sendRequestRaw (package:vm_service_client/src/scope.dart:64:23)
  <asynchronous suspension>
  #4      VMIsolateRef.invokeExtension (package:vm_service_client/src/isolate.dart:361:19)
  #5      FlutterDriver._sendCommand (package:flutter_driver/src/driver/driver.dart:437:62)
  <asynchronous suspension>
  #6      FlutterDriver.runUnsynchronized (package:flutter_driver/src/driver/driver.dart:1023:13)
  <asynchronous suspension>
  #7      main.<anonymous closure>.<anonymous closure> (file:///Users/thomasroovers/Developer/Flutter/clubapp/test_driver/main_test.dart:35:20)
  <asynchronous suspension>
  #8      Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:27)
  <asynchronous suspension>
  #9      Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:250:15)
  <asynchronous suspension>
  #10     _rootRun (dart:async/zone.dart:1124:13)
  #11     _CustomZone.run (dart:async/zone.dart:1021:19)
  #12     _runZoned (dart:async/zone.dart:1516:10)
  #13     runZoned (dart:async/zone.dart:1463:12)
  #14     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:247:5)
  #15     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:166:33)
  #16     _rootRun (dart:async/zone.dart:1124:13)
  #17     _CustomZone.run (dart:async/zone.dart:1021:19)
  #18     _runZoned (dart:async/zone.dart:1516:10)
  #19     runZoned (dart:async/zone.dart:1463:12)
  #20     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:165:13)
  <asynchronous suspension>
  #21     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:25)
  <asynchronous suspension>
  #22     new Future.<anonymous closure> (dart:async/future.dart:176:37)
  #23     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #24     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #25     _rootRun (dart:async/zone.dart:1120:38)
  #26     _CustomZone.run (dart:async/zone.dart:1021:19)
  #27     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
  #28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
  #29     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #30     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #31     _rootRun (dart:async/zone.dart:1124:13)
  #32     _CustomZone.run (dart:async/zone.dart:1021:19)
  #33     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
  #34     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
  #35     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
  #36     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
  #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


  package:flutter_driver/src/driver/driver.dart 448:7  FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1062:19                         _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 80:23              _asyncErrorWrapperHelper
  package:test_api/src/backend/invoker.dart            Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1124:13                         _rootRun
  dart:async/zone.dart 1021:19                         _CustomZone.run
  dart:async/zone.dart 1516:10                         _runZoned
  dart:async/zone.dart 1463:12                         runZoned
  package:test_api/src/backend/invoker.dart 247:5      Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 166:33    Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1124:13                         _rootRun
  dart:async/zone.dart 1021:19                         _CustomZone.run
  dart:async/zone.dart 1516:10                         _runZoned
  dart:async/zone.dart 1463:12                         runZoned
  package:test_api/src/backend/declarer.dart 165:13    Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                         _CustomZone.registerCallback
  dart:async/zone.dart 962:22                          _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                          new Timer
  dart:async/timer.dart 87:9                           Timer.run
  dart:async/future.dart 174:11                        new Future
  package:test_api/src/backend/invoker.dart 399:21     Invoker._onRun.<fn>.<fn>.<fn>

01:01 +1 -2: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Stopping application instance.
Driver tests failed: 255
```

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale nl-NL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[!] Android Studio (version 3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by mmcc007** [comment]
Did you confirm the test runs without calls to screenshots?

**Comment by troovers** [comment]
Yes, when I remove the screenshot calls from the tests, they alle pass.

Op ma 7 okt. 2019 19:33 schreef Maurice McCabe <notifications@github.com<mailto:notifications@github.com>>:

Did you confirm the test runs without calls to screenshots?

**Comment by troovers** [comment]
This can indeed be solved by implementing the changes in pull request: https://github.com/mmcc007/screenshots/commit/2a40f731493051f9a05710809c691bd1bf5c6a4e.

**Comment by robindijkhof** [comment]
@mmcc007 @troovers I'm still seeing this issue on 2.1.1
