### ISSUE TITLE
Android real device brokes the work flow

### ISSUE THREAD

**Issue by rockingdice** [mmcc007/screenshots#141]
I'm facing an exception when I'm going to do the screenshots.
Seems my connected Android device makes the workflow broken. It tries to get the android emulator id and failed - because it's a real device.
I can resolve it by unplugging the device.

```
Archiving screenshots to /Users/li9s/github/flutter_projects/mhwo/rawassets/screenshots/2019-10-15 12:46:25.592...
Unhandled exception:
command failed: exitcode=1, cmd='/Users/li9s/Library/Android/sdk/platform-tools/adb -s TEV0216C22001731 emu avd name', workingDir=.
#0      cmd (package:screenshots/src/base/process.dart:436:5)
#1      getAndroidEmulatorId (package:screenshots/src/utils.dart:202:10)
#2      _findDeviceNameOfRunningEmulator (package:screenshots/src/run.dart:564:22)
#3      findRunningDevice.<anonymous closure> (package:screenshots/src/run.dart:443:16)
#4      _ListBase&Object&ListMixin.firstWhere (dart:collection/list.dart:137:15)
#5      findRunningDevice (package:screenshots/src/run.dart:426:26)
#6      runTestsOnAll (package:screenshots/src/run.dart:196:9)
<asynchronous suspension>
#7      runScreenshots (package:screenshots/src/run.dart:105:9)
<asynchronous suspension>
#8      screenshots.<anonymous closure> (package:screenshots/src/run.dart:42:14)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:screenshots/src/base/context.dart:153:29)
<asynchronous suspension>
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     AppContext.run (package:screenshots/src/base/context.dart:152:18)
<asynchronous suspension>
#15     runInContext (package:screenshots/src/context_runner.dart:22:24)
<asynchronous suspension>
#16     screenshots (package:screenshots/src/run.dart:41:12)
<asynchronous suspension>
#17     main (file:///Users/li9s/.pub-cache/hosted/pub.flutter-io.cn/screenshots-2.0.0/bin/main.dart:72:25)
<asynchronous suspension>
#18     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

```

**Comment by mmcc007** [comment]
Added a fix for this. You can try it out with:
```
git clone https://github.com/mmcc007/screenshots.git
cd screenshots
git checkout #141_real_devices
pub global activate --source path .
```
Run on the example app using:
```
cd example
screenshots
```
(requires modifying the screenshots.yaml to config your real device) or run on your app.

Please let me know how it goes.
