### ISSUE TITLE
NoSuchMethodError when CI environment variable is not set

### ISSUE THREAD

**Issue by r1sim** [mmcc007/screenshots#146]
I just upgraded to the latest release and noticed that I was unable to take screenshots due to this error:
```
Unhandled exception:
NoSuchMethodError: The method 'toLowerCase' was called on null.
Receiver: null
Tried calling: toLowerCase()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      isCI (package:screenshots/src/utils.dart:322:37)
#2      startEmulator (package:screenshots/src/run.dart:427:7)
<asynchronous suspension>
#3      Screenshots.runTestsOnAll (package:screenshots/src/run.dart:216:21)
<asynchronous suspension>
#4      Screenshots.run (package:screenshots/src/run.dart:126:11)
<asynchronous suspension>
#5      screenshots.<anonymous closure> (package:screenshots/src/run.dart:48:26)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:153:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:tool_base/src/base/context.dart:152:18)
<asynchronous suspension>
#12     runInContext (package:screenshots/src/context_runner.dart:16:24)
<asynchronous suspension>
#13     screenshots (package:screenshots/src/run.dart:47:12)
<asynchronous suspension>
#14     main (file:///Users/simon/Documents/git/screenshots/bin/main.dart:122:25)
<asynchronous suspension>
#15     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Everything works fine when i set the "CI" environment variable to something. I guess it would be a good idea to add some kind of null check to https://github.com/mmcc007/screenshots/blob/master/lib/src/utils.dart#L322.

**Comment by mmcc007** [comment]
Thanks for pointing this out.
Fixed and released new version
