### ISSUE TITLE
Can't execute iOS Tests (.GlobalPreferences.plist)

### ISSUE THREAD

**Issue by Ahmadre** [mmcc007/screenshots#151]
I got a weird error, when I run screenshots for ios:

```bash
rebar@Rebars-MacBook-Pro atemwegsliga % screenshots
Starting flutter daemon...                                          6.1s
Clearing images in
android/fastlane/metadata/android/en-US/images/phoneScreensho
ts for 'Nexus 6P'...
Clearing images in
android/fastlane/metadata/android/en-US/images/tenInchScreens
hots for 'Nexus 9'...
Clearing images in ios/fastlane/screenshots/en-US for 'iPhone
8 Plus'...

Unhandled exception:
command failed: exitcode=1, cmd='plutil -convert json -o - /Users/XX/Library/Developer/CoreSimulator/Devices/1955E3D0-5B0B-48D2-A454-5C96991AAD76/data/Library/Preferences/.GlobalPreferences.plist', workingDir=.
#0      cmd (package:screenshots/src/utils.dart:361:5)
#1      getIosSimulatorLocale (package:screenshots/src/utils.dart:178:19)
#2      Screenshots.runTestsOnAll (package:screenshots/src/run.dart:281:27)
<asynchronous suspension>
#3      Screenshots.run (package:screenshots/src/run.dart:126:11)
<asynchronous suspension>
#4      screenshots.<anonymous closure> (package:screenshots/src/run.dart:48:26)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:153:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:tool_base/src/base/context.dart:152:18)
<asynchronous suspension>
#11     runInContext (package:screenshots/src/context_runner.dart:16:24)
<asynchronous suspension>
#12     screenshots (package:screenshots/src/run.dart:47:12)
<asynchronous suspension>
#13     main (file:///Users/XX/.pub-cache/hosted/pub.dartlang.org/screenshots-2.1.0+1/bin/main.dart:122:25)
<asynchronous suspension>
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

It worked a minute ago, but now it won't start anymore 😢.

I also saw a previous one who got this error here. But it's not solved when i open the needed ios-simulator. restarted VSCode, restarted the ios-simulator...nothing works...

**Comment by Ahmadre** [comment]
After erasing all contents and settings in my iPhone 8 Plus it worked 🎉

**Comment by mmcc007** [comment]
Great! 
I was just about to make another suggestion. Will leave it here in case it comes back.
.
.
.
The file may have gotten corrupted somehow.

Try the lint test with:
```
cd /Users/XX/Library/Developer/CoreSimulator/Devices/1955E3D0-5B0B-48D2-A454-5C96991AAD76/data/Library/Preferences
plutil -lint .GlobalPreferences.plist
```
If lint fails, make a backup and try overwriting the .GlobalPreferences.plist with a .GlobalPreferences.plist (preferably for the same simulator type) that passes the lint test.

If overwriting .GlobalPreferences.plist succeeds, it may indicate a bug in screenshots on some platforms.

**Comment by Niek** [comment]
Same problem here, macOS 10.15.2, iOS 12 and 13 emulators. What worked for me is open Simulator, go to Hardware->Erase All Content and Settings.

**Comment by mmcc007** [comment]
plutil is called by screenshots when changing locale. Should probably be making a backup of .GlobalPreferences.plist and restoring it afterwards. Might resolve this problem if it keeps happening.

Please let me know if it keeps happening.
