### ISSUE TITLE
NoSuchMethodError: The method 'group' was called on null.

### ISSUE THREAD

**Issue by Gorniv** [mmcc007/screenshots#172]
Run on example:
```bash

screenshots 
Starting flutter daemon...                                             ⣻Unhandled exception:
NoSuchMethodError: The method 'group' was called on null.
Receiver: null
Tried calling: group(1)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      getIosDevices.<anonymous closure> (package:screenshots/src/daemon_client.dart:226:28)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:221:19)
#4      getIosDevices (package:screenshots/src/daemon_client.dart:229:6)
#5      DaemonClient.start (package:screenshots/src/daemon_client.dart:39:43)
<asynchronous suspension>
#6      Screenshots.run (package:screenshots/src/run.dart:97:24)
<asynchronous suspension>
#7      screenshots.<anonymous closure> (package:screenshots/src/run.dart:48:26)
#8      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:154:29)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1465:12)
#13     AppContext.run (package:tool_base/src/base/context.dart:153:18)
#14     runInContext (package:screenshots/src/context_runner.dart:16:24)
#15     screenshots (package:screenshots/src/run.dart:47:12)
#16     main (file:///Users/gorniv/.pub-cache/hosted/pub.dartlang.org/screenshots-2.1.1/bin/main.dart:122:25)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```
<details>
  <summary>xcrun simctl list devices --json</summary>

```json
{
  "devices" : {
    "com.apple.CoreSimulator.SimRuntime.iOS-10-3" : [
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 5",
        "udid" : "27535D56-53EC-415A-888E-27A99B8525F2"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 5s",
        "udid" : "65C92101-C3FB-414D-914E-BF4B1395EC0E"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 6 Plus",
        "udid" : "002C37D5-4887-4C4F-A97F-A06573FB141F"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 6",
        "udid" : "9FEAEFDE-25C6-4607-950D-C6E0C29973A9"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 6s",
        "udid" : "FFAF3131-20CF-4CD4-940E-5840BFFEAF56"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 6s Plus",
        "udid" : "7BC57025-6798-44DE-AE00-63ECABC061C2"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone SE",
        "udid" : "F4379F82-7C47-4A96-8462-F6077F5B36E5"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 7",
        "udid" : "8C13BBAE-732F-42CA-90AB-7D22E286AF86"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 7 Plus",
        "udid" : "8C1F02B1-98D7-4D79-8D80-79B674B9DD04"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Air",
        "udid" : "A9A54FCC-236C-4482-824F-4E1FDB55E5F1"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Air 2",
        "udid" : "A68EFB80-79E5-41A2-8DF1-28EEB98DAFDA"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (9.7 inch)",
        "udid" : "A92D0F17-0323-41BF-862F-9153A7D2C343"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (12.9 inch)",
        "udid" : "EFB5F61B-1C40-4AA2-864E-92992269D93C"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad (5th generation)",
        "udid" : "81148642-C994-457D-B762-31B27A440CD6"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (12.9-inch) (2nd generation)",
        "udid" : "AAA7D6AF-169B-4A6C-B441-8719C42A9590"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (10.5-inch)",
        "udid" : "507698B3-65E1-4D31-ADD5-D0AEB1153B2C"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-13-1" : [
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 8",
        "udid" : "FBC05BCF-48CE-4844-9D46-6C77D93BD65F",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 8 Plus",
        "udid" : "E10B4C32-072A-44E5-B40F-D993629F9C51",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 11",
        "udid" : "D78056DE-0456-40AA-B307-DF07ABDA1332",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 11 Pro",
        "udid" : "DE20D97A-D424-417C-B0B4-5EA91E2DDDB7",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 11 Pro Max",
        "udid" : "E07519F6-0517-41DB-B93A-3B2610FA8917",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (9.7-inch)",
        "udid" : "82A097AF-AE49-4A0D-9670-859CF78643FB",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (11-inch)",
        "udid" : "5CF2D48A-1CBE-4EF1-B6FF-DB05A8F11D0A",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (12.9-inch) (3rd generation)",
        "udid" : "ECEFE4D3-04F0-406E-8928-9DAC5F2753FA",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Air (3rd generation)",
        "udid" : "D71B2409-0A45-4464-8E0D-6381881DBD4B",
        "availabilityError" : "runtime profile not found"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.tvOS-13-2" : [
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple TV",
        "udid" : "0102438E-F527-4551-B944-C3E44461C873"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple TV 4K",
        "udid" : "E66FED28-0648-4DD7-999A-9D77536D7387"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple TV 4K (at 1080p)",
        "udid" : "8B425E88-DA75-4D5B-AA99-6DEEE3C4C522"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-13-2" : [
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 8",
        "udid" : "63EDEF45-5363-4338-B2B1-9840C0463ECE"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 8 Plus",
        "udid" : "894E0F2A-786B-4416-B942-74F440F1ACBB"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 11",
        "udid" : "EC056567-EEDF-4B56-878E-6CF55D2EE401"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 11 Pro",
        "udid" : "A7806D7C-0C48-42E4-AAD8-D19F0DA63594"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 11 Pro Max",
        "udid" : "583AA13A-6F79-46A3-AFA7-1BC9BE9A4BB7"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (9.7-inch)",
        "udid" : "857B1FCB-F5FF-41C1-B8F3-3EBB5AAA1440"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad (7th generation)",
        "udid" : "F143DBD7-AF02-49BD-A62D-460416C34AA9"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (11-inch)",
        "udid" : "4353822F-6DAC-4892-90B7-095492E57611"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (12.9-inch) (3rd generation)",
        "udid" : "8F09E40D-9AF3-4749-AF30-2AC5C7C23DA2"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Air (3rd generation)",
        "udid" : "BB258D9A-F64F-4034-BA7D-C8EFC2025F50"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.tvOS-12-4" : [
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple TV",
        "udid" : "A4EDD3A7-7AF1-452B-9120-66DC3216DDAC",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple TV 4K",
        "udid" : "31B33943-9095-4B7D-B5DA-E7F5306D2E41",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple TV 4K (at 1080p)",
        "udid" : "8B83C368-0398-43A8-B901-2F218143C4B3",
        "availabilityError" : "runtime profile not found"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.watchOS-6-0" : [
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 5 - 40mm",
        "udid" : "854AF168-F014-43FE-9AEC-7BA4E935C67C",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 5 - 44mm",
        "udid" : "3A2215CA-E48E-4CCF-A2B7-072B5471C529",
        "availabilityError" : "runtime profile not found"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.watchOS-6-1" : [
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple Watch Series 4 - 40mm",
        "udid" : "A5F85BAE-6140-428B-9F37-709E1974E9A9"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple Watch Series 4 - 44mm",
        "udid" : "21FCF98A-631F-41D9-9D35-9609E2559FA2"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple Watch Series 5 - 40mm",
        "udid" : "33F27070-0C1E-4C32-9ABF-A3E562F435EA"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple Watch Series 5 - 44mm",
        "udid" : "DCB183AE-80E3-4CCA-9F99-DA0DAF67DF70"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-12-0" : [

    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-9-3" : [

    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-12-1" : [

    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-12-2" : [
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 5s",
        "udid" : "94FE12E8-7413-4EFF-B05F-31196F4718CE"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 6s Plus",
        "udid" : "8DB78EEA-AEB1-42D3-9C84-802E85619FC1"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 7 Plus",
        "udid" : "80A6B357-1202-431A-8CE2-A78D4A0AEF12"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone Xs",
        "udid" : "7E5A8115-165E-4B5A-BFA6-C96475507B3C"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone Xs Max",
        "udid" : "3AD11D72-B3FA-4E4C-94B3-E4E51C67250A"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (12.9-inch) (2nd generation)",
        "udid" : "B35E6C4E-4888-4B8B-B065-87FDF3BA8BB3"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (12.9-inch) (3rd generation)",
        "udid" : "42A0C978-2BE2-4C3F-98E2-0E455FD1F88C"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.watchOS-5-3" : [
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 2 - 38mm",
        "udid" : "DA7488CF-1F83-485C-B55A-76AC50E72C50",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 2 - 42mm",
        "udid" : "27DDC612-F9F9-475D-8B28-E556BB48193E",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 3 - 38mm",
        "udid" : "4898E5A6-E8FD-4A43-9647-68D4D7F26247",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 3 - 42mm",
        "udid" : "C9C299A8-CCB8-4342-AACA-C86F0E1A07ED",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 4 - 40mm",
        "udid" : "1971075B-F259-4419-BE86-B1AB04EE811E",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 4 - 44mm",
        "udid" : "9229BDD4-F921-47FA-AEBE-3093725D6137",
        "availabilityError" : "runtime profile not found"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-12-4" : [
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 5s",
        "udid" : "CAB3EF8A-6D00-4575-B5F3-1863A8BE7E4F",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 6 Plus",
        "udid" : "A127C1DC-0693-433B-BF0B-976EE6BC7B7E",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 6",
        "udid" : "6726E92D-7673-4723-B631-11EC5B25CFD3",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 6s",
        "udid" : "647FB4E9-7222-4389-BB55-70341FC66B00",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 6s Plus",
        "udid" : "BDA0DA13-DF4A-4BC6-9869-99ED190BE0E5",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone SE",
        "udid" : "39E1C7BF-5278-42A4-AC13-134152865ACD",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 7",
        "udid" : "082C2E7F-7375-46F3-A909-94CDB6BC4766",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 7 Plus",
        "udid" : "CF786803-01A8-49C2-8DC8-E30BB3400CC4",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 8",
        "udid" : "8A7BC745-BFC0-4C73-A3FB-5B4EE15FCFEE",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 8 Plus",
        "udid" : "01406972-CBDD-4B06-AA46-42FDD163071F",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone X",
        "udid" : "6DDA455E-6154-41FF-9DED-04924B931DEE",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone Xs",
        "udid" : "5421B23E-311E-4CB1-8471-F892EB14D542",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone Xs Max",
        "udid" : "B2471751-DDE2-42DA-AB09-6C158F6C54E7",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone Xʀ",
        "udid" : "D97DEFD9-86E8-4229-A36A-404BA092B79A",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Air",
        "udid" : "401AEE01-75B9-49BD-A083-961AD09CCD8D",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Air 2",
        "udid" : "F9EE21F0-EC0B-4CB7-AB81-15D2AA569F1B",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (9.7-inch)",
        "udid" : "94A24FF7-54FA-47E6-BAC7-4939DB1EC48E",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (12.9-inch)",
        "udid" : "3B096C3E-7585-4D3F-B808-07A329B75A62",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad (5th generation)",
        "udid" : "C131AB0B-BEE7-4F14-8161-558E3D9BAAD6",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (12.9-inch) (2nd generation)",
        "udid" : "91E4C91D-4984-48C8-A774-09487BDD065B",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (10.5-inch)",
        "udid" : "37443BA7-2F6F-458E-88C7-05462F72CD13",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad (6th generation)",
        "udid" : "819ECB50-C117-4DCD-A61E-77BC0343FF7F",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (11-inch)",
        "udid" : "7D1CC92E-EFA1-44D8-ADD5-2DD74C00A6E3",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (12.9-inch) (3rd generation)",
        "udid" : "F01F7FFF-F6A2-4F2F-8DAA-7CA04E9EAC4C",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Air (3rd generation)",
        "udid" : "885B1C26-5901-413C-8F0F-475393B2952E",
        "availabilityError" : "runtime profile not found"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-13-0" : [
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 11",
        "udid" : "2FF32FC1-0BF3-42BD-8FDA-19F4177C1254",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Creating",
        "isAvailable" : false,
        "name" : "iPhone 11 Pro",
        "udid" : "8FE4A6B2-D4DF-49B5-BBC8-2EAE196D6A10",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Creating",
        "isAvailable" : false,
        "name" : "iPhone 11 Pro Max",
        "udid" : "56A7052A-DF67-45D8-8E51-5E72C38BD687",
        "availabilityError" : "runtime profile not found"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-9-0" : [

    ]
  }
}
```

</details>

**Comment by mmcc007** [comment]
What does
```
ios-deploy -c
```
return?

Also
```
flutter doctor -v
```

**Comment by Gorniv** [comment]
ios-deploy -c
`[....] Waiting up to 5 seconds for iOS device to be connected`
```bash
Gorniv:example gorniv$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-RU)
    • Flutter version 1.12.13+hotfix.5 at /Users/gorniv/github/flutter
    • Framework revision 27321ebbad (6 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gorniv/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/gorniv/Library/Android/sdk
    • Java binary at: /Users/gorniv/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/gorniv/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone Xs Max • 3AD11D72-B3FA-4E4C-94B3-E4E51C67250A • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by mmcc007** [comment]
What is the return code of
```
ios-deploy -c
```
?
Should be the value of `echo $?` (expecting a non-zero number like 253)

**Comment by Gorniv** [comment]
![image](https://user-images.githubusercontent.com/963316/70941707-0f10df00-205e-11ea-96fb-0ed1788ed2a6.png)
was run 'xs max' and '8 plus'

**Comment by mmcc007** [comment]
With no real devices attached, should be getting:
```
sh -c "ios-deploy -c" || echo "no attached devices"
[....] Waiting up to 5 seconds for iOS device to be connected
no attached devices
```
Somehow you are getting something else.

Try
```
git clone https://github.com/mmcc007/screenshots
cd screenshots
git checkout 172_ios_deploy
pub global activate -s path .
```

**Comment by Gorniv** [comment]
Thank you.
This helps me.
I have "iPhone Xs Max", but use "iPhone X**S** Max"

**Comment by pontus-andersson** [comment]
@mmcc007 I had this exact issue when my iPhone was plugged into my MacBook. Disconnecting the iPhone resolved it for me.

**Comment by agordeev** [comment]
> @mmcc007 I had this exact issue when my iPhone was plugged into my MacBook. Disconnecting the iPhone resolved it for me.

Helped me too. It'd be great to mention that in docs!
