### ISSUE TITLE
failure to run example app

### ISSUE THREAD

**Issue by bsr203** [mmcc007/screenshots#176]
Thank you for this great package.

I looked through similar issues in this repo, but this may be different.
Steps: 
1. cloned the repo and cd to `example` folder
2. installed all the dependencies
3. list my emulators

> flutter emulators4 available emulators:
> 
> Pixel_2_API_28      • Pixel 2 API 28   • Google • android
> UI_Dev_API_29       • UI Dev API 29    • Google • android
> flutter_emulator    • flutter emulator • Google • android
> apple_ios_simulator • iOS Simulator    • Apple  • ios
> 
> 
4. changed the config to match it
screenshots_android.yaml
Nexus 6P -> Pixel_2_API_28

5. run `screenshots -c screenshots_android.yaml `

```
screenshots -c screenshots_android.yaml Starting flutter daemon...                                                5.8s
Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'String'
#0      Config._processDevices.<anonymous closure>.<anonymous closure> (package:screenshots/src/config.dart:150:54)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#2      Config._processDevices.<anonymous closure> (package:screenshots/src/config.dart:137:15)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#4      Config._processDevices (package:screenshots/src/config.dart:136:13)
#5      Config.devices (package:screenshots/src/config.dart:57:7)
#6      Config.androidDevices (package:screenshots/src/config.dart:60:44)
#7      isValidConfig (package:screenshots/src/validate.dart:31:46)
#8      Screenshots.run (package:screenshots/src/run.dart:109:16)
<asynchronous suspension>
#9      screenshots.<anonymous closure> (package:screenshots/src/run.dart:48:26)
#10     AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:154:29)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     AppContext.run (package:tool_base/src/base/context.dart:153:18)
#16     runInContext (package:screenshots/src/context_runner.dart:16:24)
#17     screenshots (package:screenshots/src/run.dart:47:12)
#18     main (file:///Users/bsr/.pub-cache/hosted/pub.dartlang.org/screenshots-2.1.1/bin/main.dart:122:25)
<asynchronous suspension>
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

```

screenshots -v
```
$ screenshots -v
[  +66 ms] Starting flutter daemon...
[  +11 ms] executing: flutter daemon
[ +562 ms] <== Starting device daemon...
[  +11 ms] <== [{"event":"daemon.connected","params":{"version":"0.5.3","pid":53775}}]
[   +3 ms] ==> [{"method":"device.enable","id":0}]
[        ] waiting for response: {method: device.enable, id: 0}
[  +18 ms] <== [{"id":0}]
[+5024 ms] executing: [./] sh -c ios-deploy -c || echo "no attached devices"
[   +2 ms] <== [{"event":"device.added","params":{"id":"emulator-5554","name":"Android SDK built for
x86","platform":"android-x86","emulator":true,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":"Pixel_2_API_28"}}]
[ +126 ms] Starting flutter daemon... (completed in 5.7s)
[   +1 ms] ==> [{"method":"device.getDevices","id":1}]
[        ] waiting for response: {method: device.getDevices, id: 1}
[   +5 ms] <== [{"id":1,"result":[{"id":"emulator-5554","name":"Android SDK built for
x86","platform":"android-x86","emulator":true,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":"Pixel_2_API_28"}]}]
[   +3 ms] daemonDevice=id: emulator-5554, name: Android SDK built for x86, category: mobile, platformType: android platform: android-x86, emulator: true, ephemeral: true,
emulatorId: Pixel_2_API_28, iosModel: null
[   +2 ms] ==> [{"method":"emulator.getEmulators","id":2}]
[        ] waiting for response: {method: emulator.getEmulators, id: 2}
[  +28 ms] <== [{"id":2,"result":[{"id":"Pixel_2_API_28","name":"Pixel 2 API 28","category":"mobile","platformType":"android"},{"id":"UI_Dev_API_29","name":"UI Dev API
29","category":"mobile","platformType":"android"},{"id":"flutter_emulator","name":"flutter
emulator","category":"mobile","platformType":"android"},{"id":"apple_ios_simulator","name":"iOS Simulator","category":"mobile","platformType":"ios"}]}]
[   +1 ms] daemonEmulator=id: Pixel_2_API_28, name: Pixel 2 API 28, category: mobile, platformType: android
[        ] daemonEmulator=id: UI_Dev_API_29, name: UI Dev API 29, category: mobile, platformType: android
[        ] daemonEmulator=id: flutter_emulator, name: flutter emulator, category: mobile, platformType: android
[        ] daemonEmulator=id: apple_ios_simulator, name: iOS Simulator, category: mobile, platformType: ios
Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'String'
#0      Config._processDevices.<anonymous closure>.<anonymous closure> (package:screenshots/src/config.dart:150:54)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#2      Config._processDevices.<anonymous closure> (package:screenshots/src/config.dart:137:15)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#4      Config._processDevices (package:screenshots/src/config.dart:136:13)
#5      Config.devices (package:screenshots/src/config.dart:57:7)
#6      Config.androidDevices (package:screenshots/src/config.dart:60:44)
#7      isValidConfig (package:screenshots/src/validate.dart:31:46)
#8      Screenshots.run (package:screenshots/src/run.dart:109:16)
<asynchronous suspension>
#9      screenshots.<anonymous closure> (package:screenshots/src/run.dart:42:26)
#10     AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:154:29)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     AppContext.run (package:tool_base/src/base/context.dart:153:18)
#16     runInContext (package:screenshots/src/context_runner.dart:16:24)
#17     screenshots (package:screenshots/src/run.dart:41:12)
#18     main (file:///Users/bsr/.pub-cache/hosted/pub.dartlang.org/screenshots-2.1.1/bin/main.dart:122:25)
<asynchronous suspension>
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

flutter doctor -v
```
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15 19A602, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/bsr/work/sdk/flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/bsr/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/bsr/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio
    • Android Studio at /Users/bsr/Applications/Android Studio 3.6 Preview.app/Contents
    • Flutter plugin version 42.1.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

Thank you.

**Comment by bsr203** [comment]
@mmcc007 any pointer is greatly appreciated. thanks

**Comment by tnoor-co** [comment]
@bsr203 @mmcc007  I ran into the same issue and it appears as though it may stem from the sample configuration stated in the repo readme for "orientation".

My version of '/lib/src/config.dart' does not match with the one that's on the repo leading me to think that this configuration sample is for the latest unreleased version. "Our" version only supports one orientation value as a string whereas the new version will support both.

Quick fix, remove orientation or update the value to a string =>

```
    iPad Pro (9.7-inch):
      frame: false
      orientation: Portrait 
```

Latest version using homebrew / v2.1.1: 

```
deviceProps == null
              ? null
              : deviceProps['orientation'] == null
                  ? null
                  : utils.getEnumFromString(
                      Orientation.values, deviceProps['orientation'],
                      allowNull: true),
```

git version as of 12/31/19:

```
deviceProps == null
    ? null
    : orientationVal == null
        ? null
        : orientationVal is String
            ? [_getValidOrientation(orientationVal, deviceName)]
            : List<Orientation>.from(orientationVal.map((o) {
                return _getValidOrientation(o, deviceName);
            })),
```

**Comment by bsr203** [comment]
@tnoor-co thanks for the help. After knowing the cause, I just updated it to master `pub global activate -sgit https://github.com/mmcc007/screenshots`
