### ISSUE TITLE
Test not found - _test suffix added somewhere

### ISSUE THREAD

**Issue by ykorzikowski** [mmcc007/screenshots#18]
My test is present at `test_driver/app_full_test.dart`

screenshots.yaml
```
# Screen capture tests
tests:
  - test_driver/app_full_test.dart

# Interim location of screenshots from tests
staging: /tmp/screenshots

# A list of locales supported by the app
locales:
  - de-DE
  - en-US

# A list of devices to emulate
devices:
  ios:
    - iPhone X
    #    - iPhone 7 Plus
    - iPad Pro (12.9-inch) (2nd generation)
  #   "iPhone 6",
  #   "iPhone 6 Plus",
  #   "iPhone 5",
  #   "iPhone 4s",
  #   "iPad Retina",
  #   "iPad Pro"
  android:
#    - Nexus 6P
#    - Nexus 5X

# Frame screenshots
frame: true

```

```
Yannik@workaholic:tiny_release $ screenshots
Warning: Flutter integration tests do not work in multiple locals.
  See issue: https://github.com/flutter/flutter/issues/27785 for details.
  and provide a thumbs-up to prioritize a fix for this issue!

  While waiting for a fix configure only the default locale
  in screenshots.yamlClearing images in ios/fastlane/screenshots/de-DE for 'iPhone X'...
Clearing images in ios/fastlane/screenshots/en-US for 'iPhone X'...
Clearing images in ios/fastlane/screenshots/de-DE for 'iPad Pro (12.9-inch) (2nd generation)'...
Clearing images in ios/fastlane/screenshots/en-US for 'iPad Pro (12.9-inch) (2nd generation)'...
Starting simulator 'iPhone X' in locale de-DE ...
Capturing screenshots with test test_driver/app_full_test.dart on simulator iPhone X in locale de-DE ...
Using device iPhone X.
Test file not found: /Users/Yannik/work/tiny_release/test_driver/app_full_test_test.dart
Unhandled exception:
command failed: cmd='flutter drive test_driver/app_full_test.dart'
#0      streamCmd (package:screenshots/utils.dart:66:7)
<asynchronous suspension>
#1      screenshots (package:screenshots/screenshots.dart:101:9)
<asynchronous suspension>
#2      run (package:screenshots/screenshots.dart:71:17)
#3      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#7      Future._complete (dart:async/future_impl.dart:473:7)
#8      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#9      _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#10     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#11     clearFastlaneDirs (package:screenshots/fastlane.dart)
#12     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#16     Future._complete (dart:async/future_impl.dart:473:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#20     clearFastlaneDir (package:screenshots/fastlane.dart)
#21     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#25     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:348:9)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)


```

**Comment by ykorzikowski** [comment]
FIxed this by myself. 

Remeber to rename app.dart <=> app_test.dart both when refactoring :)

**Comment by mmcc007** [comment]
I added a note to the example screenshots.yaml and updated README with your feedback ... currently in dev branch... 

thnx!

**Comment by jlubeck** [comment]
I'm not sure I understand the requirement here... or what was fixed by you @ykorzikowski 

This is how I have my tests setup (like they mention in the official [Flutter integration tests documentation](https://flutter.dev/docs/cookbook/testing/integration/introduction))
<img width="979" alt="Screen Shot 2020-05-01 at 3 27 35 PM" src="https://user-images.githubusercontent.com/3067603/80835217-525c8c00-8bc0-11ea-80e1-88cd923cd945.png">

But I'm also running into this issue:

`Test file not found: /test_driver/app_test_test.dart` (note the extra `_test`)

The interesting thing is that it does go succesufully through a first run. But then it tries again with the extra `_test` file.

Here are some logs (check the highlighted red line):

```diff
screenshots
Starting flutter daemon...                                          0.7s
Warning: using default value 'phone' in 'Nexus_6_API_28' fastlane directory.
Clearing images in
android/fastlane/metadata/android/en-US/images/phoneScreenshots for
'Nexus_6_API_28'...
Clearing images in ios/fastlane/screenshots/en-US for 'iPhone 8 Plus'...
Clearing images in ios/fastlane/screenshots/en-US for 'iPhone 11 Pro Max'...
Warning: using default value 'phone' in 'iPad Pro (12.9-inch) (4th generation)'
fastlane directory.
Clearing images in ios/fastlane/screenshots/en-US for 'iPad Pro (12.9-inch) (4th
generation)'...
Starting iPhone 8 Plus...
- Running test_driver/app.dart on 'iPhone 8 Plus' in locale en-US...
Starting application: test_driver/app.dart
Running Xcode build...                                          
Xcode build done.                                           13.3s
flutter: Observatory listening on http://127.0.0.1:55789/7Ye389ki0Zs=/
00:00 +0: NWT App (setUpAll)

VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:55789/7Ye389ki0Zs=/
VMServiceFlutterDriver: Isolate found with number: 4208370342541699
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
VMServiceFlutterDriver: Waiting for service extension
flutter: /Users/jan/Library/Developer/CoreSimulator/Devices/9B9D1FF0-4618-408C-BCC6-532714BABE1E/data/Containers/Data/Application/4ED303D9-00E9-47EC-81ED-B7D4196485F0/Documents/nwt.db
VMServiceFlutterDriver: Connected to Flutter application.
00:00 +0: NWT App check flutter driver health

00:00 +1: NWT App WelcomeScreen

00:05 +2: NWT App PinScreen

VMServiceFlutterDriver: waitFor message is taking a long time to complete...
We are not in the Pin Screen

00:06 +3: NWT App home

Screenshot 01.Profile created

Screenshot 02.Update created

Screenshot 03.Timeline created

00:14 +4: NWT App (tearDownAll)

00:14 +4: All tests passed!

Stopping application instance.
Warning: framing is not enabled
Moving screenshots to ios/fastlane/screenshots/en-US
- Running test_driver/app_test.dart on 'iPhone 8 Plus' in locale en-US...
- Test file not found: /Users/jan/Projects/flutter/net_worth_tracker/test_driver/app_test_test.dart
Unhandled exception:
command failed: exitcode=1, cmd='flutter -d 9B9D1FF0-4618-408C-BCC6-532714BABE1E drive test_driver/app_test.dart', workingDirectory=null, mode=normal
#0      streamCmd (package:screenshots/src/utils.dart:468:7)
<asynchronous suspension>
#1      Screenshots.runProcessTests (package:screenshots/src/run.dart:415:13)
<asynchronous suspension>
#2      Screenshots.runTestsOnAll (package:screenshots/src/run.dart:362:19)
<asynchronous suspension>
#3      Screenshots.run (package:screenshots/src/run.dart:127:11)
<asynchronous suspension>
#4      screenshots.<anonymous closure> (package:screenshots/src/run.dart:48:26)
#5      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:154:29)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZoned (dart:async/zone.dart:1539:10)
#10     AppContext.run (package:tool_base/src/base/context.dart:153:18)
#11     runInContext (package:screenshots/src/context_runner.dart:17:24)
#12     screenshots (package:screenshots/src/run.dart:47:12)
#13     main (file:///Users/jan/.pub-cache/git/screenshots-d542991cf0d6fa10897746695f0aa4ed8bb973b4/bin/main.dart:122:25)
<asynchronous suspension>
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

So how should I fix this?

**Comment by jlubeck** [comment]
Wow, stupid me... It was just a matter of removing the line `  - test_driver/app_test.dart`

The documentation `# Note: flutter driver expects a pair of files eg, main.dart and main_test.dart` makes me think that both files were needed there
