### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by jlubeck** [mmcc007/screenshots#195]
When I execute `screenshots` the emulator opens up, but then almost immediately errors out

Here are the logs of `screenshots -v`

```
screenshots -v
[  +40 ms] Starting flutter daemon...
[  +12 ms] executing: flutter daemon
[ +591 ms] <== Starting device daemon...
[   +1 ms] <==
[{"event":"daemon.connected","params":{"version":"0.5.3","pid":37838}}]
[   +7 ms] ==> [{"method":"device.enable","id":0}]
[  +15 ms] <== [{"id":0}]
[   +8 ms] executing: sh -c ios-deploy -c || echo "no attached devices"
[ +117 ms] Starting flutter daemon... (completed in 0.7s)
[        ] ==> [{"method":"device.getDevices","id":1}]
[   +3 ms] <== [{"id":1,"result":[]}]
[   +1 ms] ==> [{"method":"emulator.getEmulators","id":2}]
[  +39 ms] <== [{"id":2,"result":[{"id":"Nexus_6_API_28","name":"Nexus 6 API
28","category":"mobile","platformType":"android"},{"id":"Pixel_2","name":"Pixel
2","category":"mobile","platformType":"android"},{"id":"apple_ios_simulator","na
me":"iOS Simulator","category":"mobile","platformType":"ios"}]}]
[   +1 ms] daemonEmulator=id: Nexus_6_API_28, name: Nexus 6 API 28, category:
mobile, platformType: android
[        ] daemonEmulator=id: Pixel_2, name: Pixel 2, category: mobile,
platformType: android
[        ] daemonEmulator=id: apple_ios_simulator, name: iOS Simulator,
category: mobile, platformType: ios
[  +23 ms] executing: chmod u+x
/tmp/screenshots/resources/script/android-wait-for-emulator
[   +9 ms] executing: chmod u+x
/tmp/screenshots/resources/script/android-wait-for-emulator-to-stop
[   +9 ms] executing: chmod u+x
/tmp/screenshots/resources/script/simulator-controller
[   +7 ms] executing: chmod u+x
/tmp/screenshots/resources/script/sim_orientation.scpt
[   +5 ms] Warning: using default value 'phone' in 'Pixel_2' fastlane directory.
[        ] Clearing images in
           android/fastlane/metadata/android/en-US/images/phoneScreenshots for
'Pixel_2'...
[   +4 ms] Starting Pixel_2...
[   +1 ms] ==>
[{"method":"emulator.launch","params":{"emulatorId":"Pixel_2"},"id":3}]
[+2395 ms] <==
[{"event":"daemon.logMessage","params":{"level":"error","message":"The Android
emulator exited with code 1 during startup"}}]
[        ] Warning: ignoring log message:
[{"event":"daemon.logMessage","params":{"level":"error","message":"The Android
emulator exited with code 1 during startup"}}]
[        ] <==
[{"event":"daemon.logMessage","params":{"level":"error","message":"Android
emulator stderr:"}}]
[        ] Warning: ignoring log message:
[{"event":"daemon.logMessage","params":{"level":"error","message":"Android
emulator stderr:"}}]
[        ] <==
[{"event":"daemon.logMessage","params":{"level":"error","message":"Address these
issues and try again."}}]
[        ] Warning: ignoring log message:
[{"event":"daemon.logMessage","params":{"level":"error","message":"Address these
issues and try again."}}]
[ +633 ms] <== [{"id":3}]
[ +873 ms] <==
[{"event":"device.added","params":{"id":"chrome","name":"Chrome","platform":"web
-javascript","emulator":false,"category":"web","platformType":"web","ephemeral":
false,"emulatorId":null}}]
Unhandled exception:
Error: emulator Pixel_2 not started: [{"event":"device.added","params":{"id":"chrome","name":"Chrome","platform":"web-javascript","emulator":false,"category":"web","platformType":"web","ephemeral":false,"emulatorId":null}}]
#0      DaemonClient.launchEmulator (package:screenshots/src/daemon_client.dart:85:7)
<asynchronous suspension>
#1      startEmulator (package:screenshots/src/run.dart:446:31)
#2      Screenshots.runTestsOnAll (package:screenshots/src/run.dart:217:21)
#3      Screenshots.run (package:screenshots/src/run.dart:127:11)
<asynchronous suspension>
#4      screenshots.<anonymous closure> (package:screenshots/src/run.dart:42:26)
#5      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:154:29)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZoned (dart:async/zone.dart:1539:10)
#10     AppContext.run (package:tool_base/src/base/context.dart:153:18)
#11     runInContext (package:screenshots/src/context_runner.dart:17:24)
#12     screenshots (package:screenshots/src/run.dart:41:12)
#13     main (file:///Users/jan/.pub-cache/git/screenshots-d542991cf0d6fa10897746695f0aa4ed8bb973b4/bin/main.dart:122:25)
<asynchronous suspension>
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

**Comment by kauaicreative** [comment]
I am having the same issue. 

Here is my specific version of this error:

```
Starting Nexus 6P...
Unhandled exception:
Error: emulator Nexus_6P not started: [{"event":"device.added","params":{"id":"8BDY0XPNJ","name":"Pixel 3 XL","platform":"android-arm64","emulator":false,"catego
ry":"mobile","platformType":"android","ephemeral":true,"emulatorId":null}}]
#0      DaemonClient.launchEmulator (package:screenshots/src/daemon_client.dart:85:7)
<asynchronous suspension>
#1      startEmulator (package:screenshots/src/run.dart:446:31)
```

**Comment by kauaicreative** [comment]
I now see that it only fails if a physical device is available.
Related issue #185
