### ISSUE TITLE
VMServiceFlutterDriver: waitForCondition message is taking a long time to complete...

### ISSUE THREAD

**Issue by nikunjramiindianic** [mmcc007/screenshots#205]
import 'dart:io';

import 'package:flutter_driver/flutter_driver.dart';
import 'package:screenshots/screenshots.dart';
import 'package:test/test.dart';

void main() {
  group('Customer App Test', () {
    FlutterDriver driver;
    //Map localizations;
    final config = Config();

    setUpAll(() async {
      // Connect to a running Flutter application instance.
      driver = await FlutterDriver.connect();
    });

   

    test('Home screen screenshot', () async {
      print("sleep start");
      sleep(Duration(seconds: 5));
      print("sleep end");
      await driver.runUnsynchronized(() async {
        final cardSettingsItem = find.byValueKey('home0');
        print("cardSettingsItem >> $cardSettingsItem");
      
      });

      await driver.runUnsynchronized(() async {
        await screenshot(driver, config, 'home');
      });

      await driver.runUnsynchronized(() async {
        final cardSettingsItem = find.byValueKey('home0');
        print("cardSettingsItem >> $cardSettingsItem");
        await driver.tap(cardSettingsItem);
      });

      // increase timeout from 30 seconds for testing
      // on slow running emulators in cloud
    },timeout:  Timeout(Duration(minutes: 1)));

     tearDownAll(() async {
      if (driver != null) await driver.close();
    });
  },timeout:  Timeout(Duration(minutes: 5)));
}

[+28057 ms] VMServiceFlutterDriver: waitForCondition message is taking a long time to complete...
[ +676 ms] 00:31 +0 -1: Customer App Test Home screen screenshot [E]
[        ]   DriverError: Error in Flutter application: Timeout while executing waitForCondition: TimeoutException after
0:00:30.000000: Future not completed
[  +17 ms]   package:flutter_driver/src/driver/vmservice_driver.dart 341:7  VMServiceFlutterDriver.sendCommand
[        ]   ===== asynchronous gap ===========================
[        ]   dart:async/zone.dart 1118:19                                   _CustomZone.registerBinaryCallback
[        ]   dart:async-patch/async_patch.dart 88:23                        _asyncErrorWrapperHelper
[        ]   package:test_api/src/backend/invoker.dart                      Invoker.waitForOutstandingCallbacks.<fn>
[        ]   dart:async/zone.dart 1184:13                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   dart:async/zone.dart 1619:10                                   _runZoned
[        ]   dart:async/zone.dart 1539:10                                   runZoned
[        ]   package:test_api/src/backend/invoker.dart 243:5                Invoker.waitForOutstandingCallbacks
[        ]   package:test_api/src/backend/declarer.dart 170:33              Declarer.test.<fn>.<fn>
[        ]   dart:async/zone.dart 1184:13                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   dart:async/zone.dart 1619:10                                   _runZoned
[        ]   dart:async/zone.dart 1539:10                                   runZoned
[        ]   package:test_api/src/backend/declarer.dart 169:13              Declarer.test.<fn>
[        ]   package:test_api/src/backend/invoker.dart 400:30               Invoker._onRun.<fn>.<fn>.<fn>.<fn>
[        ]   dart:async/future.dart 176:37                                  new Future.<fn>
[        ]   package:stack_trace/src/stack_zone_specification.dart 209:15   StackZoneSpecification._run
[        ]   package:stack_trace/src/stack_zone_specification.dart 119:48   StackZoneSpecification._registerCallback.<fn>
[        ]   dart:async/zone.dart 1180:38                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
[        ]   dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
[        ]   package:stack_trace/src/stack_zone_specification.dart 209:15   StackZoneSpecification._run
[        ]   package:stack_trace/src/stack_zone_specification.dart 119:48   StackZoneSpecification._registerCallback.<fn>
[        ]   dart:async/zone.dart 1184:13                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   dart:async/zone.dart 1003:23                                   _CustomZone.bindCallback.<fn>
[        ]   dart:async-patch/timer_patch.dart 23:15                        Timer._createTimer.<fn>
[        ]   dart:isolate-patch/timer_impl.dart 398:19                      _Timer._runTimers
[        ]   dart:isolate-patch/timer_impl.dart 429:5                       _Timer._handleMessage
[   +6 ms]   dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
[        ]   ===== asynchronous gap ===========================
[        ]   dart:async/zone.dart 1101:19                                   _CustomZone.registerCallback
[        ]   dart:async/zone.dart 1018:22                                   _CustomZone.bindCallbackGuarded
[        ]   dart:async/timer.dart 54:45                                    new Timer
[        ]   dart:async/timer.dart 91:9                                     Timer.run
[        ]   dart:async/future.dart 174:11                                  new Future
[        ]   package:test_api/src/backend/invoker.dart 399:21               Invoker._onRun.<fn>.<fn>.<fn>
[        ]   dart:async/zone.dart 1184:13                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   dart:async/zone.dart 1619:10                                   _runZoned
[        ]   dart:async/zone.dart 1539:10                                   runZoned
[        ]   package:test_api/src/backend/invoker.dart 387:9                Invoker._onRun.<fn>.<fn>
[        ]   package:test_api/src/backend/invoker.dart 438:15               Invoker._guardIfGuarded
[        ]   package:test_api/src/backend/invoker.dart 386:7                Invoker._onRun.<fn>
[        ]   package:stack_trace/src/chain.dart 101:24                      Chain.capture.<fn>
[        ]   dart:async/zone.dart 1184:13                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   dart:async/zone.dart 1619:10                                   _runZoned
[        ]   dart:async/zone.dart 1539:10                                   runZoned
[        ]   package:stack_trace/src/chain.dart 99:12                       Chain.capture
[        ]   package:test_api/src/backend/invoker.dart 385:11               Invoker._onRun
[        ]   package:test_api/src/backend/live_test_controller.dart 197:11  LiveTestController._run
[        ]   package:test_api/src/backend/live_test_controller.dart 50:37   _LiveTest.run
[        ]   dart:async/future.dart 202:37                                  new Future.microtask.<fn>
[        ]   dart:async/zone.dart 1180:38                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
[        ]   dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
[        ]   dart:async/zone.dart 1184:13                                   _rootRun
[   +2 ms]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[   +2 ms]   dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
[        ]   dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
[        ]   dart:async/schedule_microtask.dart 43:21                       _microtaskLoop
[        ]   dart:async/schedule_microtask.dart 52:5                        _startMicrotaskLoop
[        ]   dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
[        ]   dart:isolate-patch/timer_impl.dart 405:11                      _Timer._runTimers
[        ]   dart:isolate-patch/timer_impl.dart 429:5                       _Timer._handleMessage
[        ]   dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
[        ] 00:31 +0 -1: Customer App Test (tearDownAll)
[  +11 ms] 00:31 +0 -1: Some tests failed.
[        ] Unhandled exception:
[        ] Dummy exception to set exit code.
[  +54 ms] Stopping application instance.
[   +7 ms] Driver tests failed: 255
Unhandled exception:
command failed: exitcode=255, cmd='flutter -d 6FA3AEC2-0C78-42AE-B3E8-CABDC8A3D5FF drive test_driver/main.dart', workingDirectory=null, mode=normal
#0      streamCmd (package:screenshots/src/utils.dart:468:7)
<asynchronous suspension>
#1      Screenshots.runProcessTests (package:screenshots/src/run.dart:415:13)
#2      Screenshots.runTestsOnAll (package:screenshots/src/run.dart:362:19)
<asynchronous suspension>
#3      Screenshots.run (package:screenshots/src/run.dart:127:11)
<asynchronous suspension>
#4      screenshots.<anonymous closure> (package:screenshots/src/run.dart:42:26)
#5      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:154:29)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZoned (dart:async/zone.dart:1539:10)
#10     AppContext.run (package:tool_base/src/base/context.dart:153:18)
#11     runInContext (package:screenshots/src/context_runner.dart:17:24)
#12     screenshots (package:screenshots/src/run.dart:41:12)
#13     main (file:///Users/indianic/.pub-cache/git/screenshots-d542991cf0d6fa10897746695f0aa4ed8bb973b4/bin/main.dart:122:25)
<asynchronous suspension>
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by nikunjramiindianic** [comment]
Solved: There is continuous skeleton animation in the image background so the screenshot is not working. once I update the skeleton implementation, the screenshot starts working.
