### ISSUE TITLE
NoSuchMethodError: The method '[]'  was called on null.

### ISSUE THREAD

**Issue by lastday4you** [mmcc007/screenshots#83]
after the normal installation from the example, this is the error that I got from screenshots version 1.1.1
```
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("name")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _findDevice.<anonymous closure> (package:screenshots/src/run.dart:257:60)
#2      _ListBase&Object&ListMixin.firstWhere (dart:collection/list.dart:137:15)
#3      _findDevice (package:screenshots/src/run.dart:245:26)
#4      runTestsOnAll (package:screenshots/src/run.dart:102:20)
<asynchronous suspension>
#5      run (package:screenshots/src/run.dart:54:9)
<asynchronous suspension>
#6      main (file:///Users/keanghok/.pub-cache/hosted/pub.dartlang.org/screenshots-1.1.1/bin/main.dart:86:9)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by lastday4you** [comment]
sorry got fixed by restarting the computer may be due to some cache problem
