### ISSUE TITLE
Flutter Daemon is not starting

### ISSUE THREAD

**Issue by JtheSaw** [mmcc007/screenshots#87]
Hi, I am getting stuck on running the plugin at the point where the flutter daemon is supposed to be starting.

```
Starting flutter daemon...
Unhandled exception:
ProcessException: No such file or directory
  Command: flutter daemon
#0      DaemonClient.start (package:screenshots/src/daemon_client.dart:32:18)
<asynchronous suspension>
#1      run (package:screenshots/src/run.dart:33:22)
<asynchronous suspension>
#2      main (file:///Users/jonas.hoefer/.pub-cache/hosted/pub.dartlang.org/screenshots-1.2.0/bin/main.dart:82:9)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Here is my `flutter doctor -v`:

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.4 18E226, locale de-DE)
    • Flutter version 1.7.8+hotfix.3 at /Users/jonas.hoefer/Dev/flutter
    • Framework revision b712a172f9 (8 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jonas.hoefer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_SDK_ROOT = /Users/jonas.hoefer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!
```

Any suggestions how to solve this?
Thank you

**Comment by JtheSaw** [comment]
Nevermind. My `PATH` variable did contain `~`instead of `/Users/<username>`
